# Generated by Django 3.0.5 on 2020-05-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0003_terminal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminal',
            name='version_SO',
            field=models.IntegerField(),
        ),
    ]
