# Generated by Django 3.0.5 on 2020-05-01 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0004_auto_20200501_1329'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Terminal',
        ),
    ]
